#pragma config(Sensor, in1,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in2,    gyroSensor,     sensorGyro)
#pragma config(Sensor, I2C_1,  leftShooterEncoder, sensorNone)
#pragma config(Sensor, I2C_2,  driveFrontLeftEncoder, sensorNone)
#pragma config(Sensor, I2C_3,  driveRearLeftEncoder, sensorNone)
#pragma config(Sensor, I2C_4,  driveRearRightEncoder, sensorNone)
#pragma config(Sensor, I2C_5,  driveFrontRightEncoder, sensorNone)
#pragma config(Sensor, I2C_6,  rightShooterEncoder, sensorNone)
#pragma config(Motor,  port1,           triangularFeed, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           launcherFrontRight, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           launcherFrontLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           driveFrontRight, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           driveFrontLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           driveRearRight, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           driveRearLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,           launcherRearRight, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           launcherRearLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          magazine,      tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnClockwise (int goRight)    {
//	while(SensorValue[driveFrontRightEncoder] < goRight)   {
	while (0 < goRight)   {
  	motor[driveFrontRight] = 0;	// 5
		motor[driveRearRight] = 0;
		motor[driveFrontLeft] = 20;	// 5
		motor[driveRearLeft] = 20;

		//Starting the intake of balls
//			autoShooterStartSoft(90);		//Reve up
			//motor[triangularFeed] = 100;
			motor[magazine] = 100;
//			autoShooterStartSoft(90);
    }
}

void turnCounterClockwise (int goLeft)  {
    //while(SensorValue[driveFrontLeftEncoder] < goLeft)    {
    while (0 < goLeft)    {
		  motor[driveFrontRight] = 20;	// 5
			motor[driveRearRight] = 20;
			motor[driveFrontLeft] = 0;	// 5
			motor[driveRearLeft] = 0;

			//Starting the intake of balls
//			autoShooterStartSoft(90);		//Reve up
			//motor[triangularFeed] = 100;
			motor[magazine] = 100;
//			autoShooterStartSoft(90);
    }
}

void goForward (int goCount)    {
    //while(SensorValue[driveFrontLeftEncoder] < goCount)   {
    while (0 < goCount)   {
		  motor[driveFrontRight] = 10;	// 5
			motor[driveRearRight] = 10;
			motor[driveFrontLeft] = 10;	// 5
			motor[driveRearLeft] = 10;
			//Starting the intake of balls
//			autoShooterStartSoft(90);		//Reve up
			//motor[triangularFeed] = 100;
			motor[magazine] = 100;
//			autoShooterStartSoft(90);
		}
}

task main()	{
//----------------------------LINE SENSOR CODE----------------//
	while (true) {
		if (SensorValue(lineSensor) < 1802) {           	 // 128 to 255 is left side
			turnCounterClockwise(10);
			motor[magazine] = 100;
			wait1Msec(1500);
		}
		else if (SensorValue(lineSensor) >= 1802 && SensorValue(lineSensor) <= 1929)	{
			goForward(10);
			wait1Msec(1500);
		}
		else if (SensorValue(lineSensor) > 1929) {           // 0 to 127 is the right side.
			turnClockwise(10);
			wait1Msec(1500);
		}
		//else if (SensorValue(lineSensor) > 1750)	{	// this will be the white line. MAYBE? SHOOT SHOOOOOTTT PLZZZZ
		//	motor[driveFrontRight] = 0;
		//	motor[driveRearRight] = 0;
		//	motor[driveFrontLeft] = 0;
		//	motor[driveRearLeft] = 0;
		//	//	TURN 45 WITH gyroSensor

		//	motor[magazine] = 100;
		//	wait1Msec(3000);
		//}
		else    {   			//I Dont know what could be else.
			motor[driveFrontRight] = 0;
			motor[driveRearRight] = 0;
			motor[driveFrontLeft] = 0;
			motor[driveRearLeft] = 0;
			motor[magazine] = 100;
			wait1Msec(3000);
			}
		}   // end Line Sensor statement
	}



// StartTask(serialRxTask);	//gyroSensor

/*
int preloads = 0;
while (preloads <= 3)	{
		autoShooterStartSoft(90);
		wait1Msec(3000);

		motor[magazine] = 100;
		wait1Msec(2500);

		motor[magazine] = 0;
		wait1Msec(1500);
	}

		motor[magazine] = 0;
		motor[shooterLeft] = 0;
		motor[shooterRight] = 0;
		motor[magazine] = 0;
		wait1Msec(3000);


		motor[driveFrontRight] = 100;
		motor[driveRearRight] = 100;
		motor[driveFrontLeft] = 100;
		motor[driveRearLeft] = 100;
		wait1Msec(1000);	//	1 second of going forward

		//wait1Msec(5000);

		*/
