#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, I2C_1,  LE,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RE,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           driveFrontRight, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           shooter,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           shooter,       tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveRearLeft, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           driveRearRight, tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// proportional comtrol for the shooter


int derivative = 5;
int proportion = 5;
int targetSpeed = 11;
int leftEncoderSpeed;
int rightEncoderSpeed;
int leftEncoderError ;
int rightEncoderError ;
int leftVelocity = 80; // initial speeds
int rightVelocity = 80;
int leftEncoderErrorOld;
int rightEncoderErrorOld;
int leftEncoderDerivativeError;
int rightEncoderDerivativeError;
void runShooter(int leftSpeed,  int rightSpeed) // function to run shooter motors
{
	if(leftSpeed > 80){
		leftSpeed = 80;
	}
	if(leftSpeed < -80){
		leftSpeed = -80;
	}
	if(rightSpeed > 80){
		rightSpeed = 80;
	}
	if(rightSpeed < -80){
		rightSpeed = -80;
	}
	motor[LT] = leftSpeed;
	motor[RT] = rightSpeed;
}
task main()
{
	ClearTimer(T2);
	SensorValue[LE] = 0;	// is there a sensor for
	SensorValue[RE] = 0;
	while(true){
		runShooter(leftVelocity,rightVelocity);
		//if(time10[T2] == 10){
			leftEncoderSpeed = -SensorValue[LE];
			rightEncoderSpeed = SensorValue[RE];
			leftEncoderError = targetSpeed - leftEncoderSpeed;
			rightEncoderError  = targetSpeed - rightEncoderSpeed;
			leftEncoderDerivativeError = leftEncoderError - leftEncoderErrorOld;
			rightEncoderDerivativeError = rightEncoderError - rightEncoderErrorOld;
			leftEncoderErrorOld = leftEncoderError;
			rightEncoderErrorOld = rightEncoderError;
			SensorValue[LE] = 0;
 			SensorValue[RE] = 0;
			leftVelocity = leftVelocity + proportion*leftEncoderError/20 + derivative*leftEncoderDerivativeError/4;
			rightVelocity = rightVelocity + proportion*rightEncoderError/20 + derivative*rightEncoderDerivativeError/4;
			wait10Msec(2);

	}


}
