#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, I2C_1,  RE,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  LE,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           driveFrontRight, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveRearLeft, tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           driveRearRight, tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "serialCortex.h"

// int x; // what is this.
//int y;

/* task main()
{
	ClearTimer(T1);

		while(time10[T1] < 501){
			motor[RT] = 60;
			motor[RB] = -60;
			motor[LT] = -60;
			motor[LB] = 60;
			if(time10[T1] == 500){
				x = SensorValue[RE]/5;
				y = SensorValue[LE]/(5);
				ClearTimer(T1);
				SensorValue[RE] = 0;
				SensorValue[LE] = 0;
			}
		}
} */
// Begin User Control.

task main()
{
	int left_motor_value;
	int right_motor_value;
	float angle;

	// init everything
	Do_all_initialization();

	while (true)
	{
		//Driving Motor Control
		motor[RT] = 60;
		motor[RB] = -60;
		motor[LT] = -60;
		motor[LB] = 60;

		// get the angle of the robot
		angle = StartTask(serialRxTask);

		// check angle - depends on how it is mounted
		// angle is in range 0 - 360
		if ((angle > 15.0) && (angle < 180.0))
		{
			// modify the motor commands if it is backwards
			// you may want to check for forward or backward motion as well
			left_motor_value = -100;
			right_motor_value = -100;
		}
		// send to motors
		motor[LR] = left_motor_value;
		motor[LT] = left_motor_value;
		motor[RT] = right_motor_value;
		motor[RB] = right_motor_value;

		//Arm Control

		//Intake Roller
	}
}
