#pragma config(Sensor, in1,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in2,    leftEncoder,    sensorNone)
#pragma config(Sensor, in3,    rightEncoder,   sensorNone)
#pragma config(Sensor, in4,    touchSensor,    sensorNone)
#pragma config(Motor,  port2,           RIGHT,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           LEFT,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void turnClockwise (int goRight)    {

    while(SensorValue[leftEncoder] < goRight)   {
    motor[RIGHT] = -30;     // RIGHT
    motor[LEFT] = 40;       // LEFT
    }
}

void turnCounterClockwise (int goLeft)  {
    while(SensorValue[leftEncoder] < goLeft)    {
        motor[RIGHT] = 120;         //RIGHT SOFTLY POWOER
        motor[LEFT] = -120;     //LEFT
    }
}

void goForward (int goCount)    {
    while(SensorValue[leftEncoder] < goCount)   {       //goCount is 1 block
        motor[RIGHT] = 56;      //Motor on RIGHT is run at full (70) power
        motor[LEFT] = 102;      //Motor on LEFT is run at full (127) power forward
        if(SensorValue(lineSensor) > 1) {           // BLACK VALUE
            wait1Msec (2000);                                   // WAIT 20 seconds before starting
            turnCounterClockwise(15);
            } // end if (lineSensor)
        }  // end if(SensorValue(TouchSensor) == 1)
    }

task main() {
 while(true)        {
   if(SensorValue(lineSensor) < 127) {           	 // 128 to 255 is left side
		turnCounterClockwise(15);
            } 
	else if (SensorValue(lineSensor) > 127) {           // 0 to 127 is the right side.  
		turnClockwise(15);
		} 
        else    {               // BREAK
            motor[RIGHT] = 0;
            motor[LEFT] = 0;
        }   // end else statement
    }   // end  while(true)
}



   /* TOUCH SENSOR*/
   /*
        if(SensorValue(touchSensor) == 1)   {       // PUSH to turn on
            wait1Msec (2000);                                   // WAIT 20 seconds before starting
            SensorValue[leftEncoder] = 0;           // reseting the encoder before use
            goForward(850);

    }


/*  OLD line sensor program (Goes into main) **
    while(true)
    {
        int x = 0;
        if(SensorValue(lineSensor) > 600)   {           // BLACK VALUE
            x = 0;
            turnClockwise(15);
            }
        else    {
            if (x == 1) {
                turnClockwise(15);
            }
            else    {
            turnCounterClockwise(15);   // turn LEFT
            }
        }//end else loop
    } //end while loop
*/
