#pragma config(Sensor, in1,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in2,    leftEncoder,    sensorNone)
#pragma config(Sensor, in3,    rightEncoder,   sensorNone)
#pragma config(Sensor, in4,    touchSensor,    sensorNone)
#pragma config(Motor,  port2,           RIGHT,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           LEFT,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
 while(true)        {
	if(SensorValue(lineSensor) == 1)   {
		motor[port2] = 127;	
	}

